### ISSUE TITLE
[Unrelated] Contact information?

### ISSUE THREAD

**Issue by edgar-vincent** [gallofeliz/syaning-cli-loader#1]
Hello, 

I'm sorry, this issue is not related to this project, but I haven't found more appropriate means of contacting you. 
I would like to ask you about the licensing of https://github.com/gallofeliz/simple-docker-webdav which doesn't have an "Issues" page. 

Thanks,

EV

**Comment by gallofeliz** [comment]
Hi,

I have activated just now the issues section.

The simplest answer is that you can considerate the license is MIT (like its parent) and feel free to use it and modify it !

The less simple answer is that the code is very small and nothing original, even if I say "NO", it's a basic nginx config with a small init script ;)

Thanks for you answer, have a good day,

Regards

**Comment by edgar-vincent** [comment]
That's what I thought, but I wanted to make sure :)

Thanks a lot for your prompt reply.

EV
